var configuration = {
	program: "WEB",
	//program: "UIUX",
	//program: "no",
	activityName: "",
	ActivityDescription: `La creación de páginas web no sólo se limita a la estructuración de un diseño básico y la ubicación de los contenidos en los diferentes espacios y contenedores que definamos, sinó que también consta de optar por mostrar los datos relevantes en los momentos adecuados para optimizar la experiencia de los usuarios. Esto quiere decir que el desarrollador debe ser consciente de qué contenidos mostrar u ocultar de acuerdo con el tipo de información que la persona que accede al portal desea o necesita observar.
<br><br>jQuery cuenta con un conjunto de métodos que muestran y ocultan elementos del DOM, dando la posibilidad de personalizar la forma en cómo se realizan estas acciones, el tiempo de duración, la uniformidad en la velocidad de la operación, y definir mediante un callback qué acciones realizar una vez finalice el efecto.<br><br>Durante los videos de esta lección pudiste observar que estábamos desarrollando un videojuego educativo para niños con animales de la granja. En este ejercicio debes ayudar a terminar el desarrollo de este juego, implementando mediante jQuery, algunas funciones adicionales para darle completa funcionalidad al proyecto.
<center><img src="img1.png" style="width: 550px"></center>`,
	goodp: ["Recuerda que JavaScript es un lenguaje asíncrono, lo que quiere decir que la ejecución de las funciones y métodos no necesariamente se da en el orden en el que las ubicas en el código. Por tal razón, es muy importante hacer uso de los callbacks, los cuales son funciones que se ejecutan al finalizar una acción, teniendo mayor control en el orden de ejecución de las acciones en la página."], // el texto Buenas Prácticas no irá si este array está vacio o no está
	instructions : ['Al presionar el botón de cada animal, debe aparecer la imagen con el id vaca, cerdo, gallina u oveja, según corresponda. Al presionar nuevamente el botón, si la imágen está mostrada, debe esconderse. Al finalizar la acción debe mostrarse el letrero: <ul> <li>La vaca hace muuu</li><li>El cerdo hace oink</li><li>La gallina hace cloac</li><li>La oveja hace beee</li></ul>Según corresponda.<center><img src="img2.png" style="width: 550px"></center>','Al presionar el botón con el ícono de las tijeras, el cursor debe cambiar su apariencia a las de unas tijeras. Dicho ícono se encuentra dentro de la carpeta de imágenes incluida en los archivos que descargaste del código base.<center><img src="img3.png" style="width: 550px"></center>','Al presionar el botón con el ícono de la herramienta, el cursor debe cambiar su apariencia al ícono de la herramienta, también localizado en la carpeta de imágenes; además debe mostrar los elementos de la clase cerca y animalP, adicionalmente cambiar el título de la página para que diga “Construye una cerca” una vez finalice la animación.<center><img src="img4.png" style="width: 550px"></center>','Si el cursor está en forma de tijeras, al posar el mouse encima de los arbustos, éstos deben desaparecer.<br><br><center><video width="400"   controls><source src="4.mp4" type="video/mp4"></video></center>','Drag and Drop. En el modo de construcción, al presionar el botón de la herramienta, debes hacer que los elementos de la cerca, y las imágenes pequeñas de los animales se puedan arrastrar y soltar en la posición que se quiera.<br><br><center><video width="400"   controls><source src="5.mp4" type="video/mp4"></video></center>','Al hacer click en el ícono listo, se debe esconder todo cuanto elemento esté mostrado en la página y cambiar el título a “Muy Bien!” una vez termine la animación.<br><br><center><video width="400"   controls><source src="6.mp4" type="video/mp4"></video></center>','Cuando no esté el mouse en el modo cortar o construir, el cursor debe retornar a su aspecto normal.'], // el texto Instrucciones no irá si este array está vacio o no está
	type: "exercise-code",
	time: [45,'min.','minutos'],
	solution: 'solucion/NextUsolucionMostrarOcultar.zip',  // si no está o está vacio no aparecerá
	base : 'solucion/NextUcodBaseMostrarOcultar.zip' // si no está o está vacio no aparecerá
}

$.getScript( "../../includes/js/" + configuration.type + ".js" )
$('.backdrop').on('click', function() {
	$('#alert').toggleClass('active');
})
